<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-27T12:23:46Z" name="Default suite" finished-at="2021-06-27T12:24:00Z" duration-ms="14339">
    <groups>
    </groups>
    <test started-at="2021-06-27T12:23:46Z" name="Default test" finished-at="2021-06-27T12:24:00Z" duration-ms="14339">
      <class name="qa.testscripts.AUT1">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:qa.testscripts.AUT1@63f259c3]" started-at="2021-06-27T12:23:45Z" name="beforeSuite" finished-at="2021-06-27T12:23:46Z" duration-ms="1379" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:qa.testscripts.AUT1@63f259c3]" started-at="2021-06-27T12:23:46Z" name="beforeTest" finished-at="2021-06-27T12:23:46Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:qa.testscripts.AUT1@63f259c3]" started-at="2021-06-27T12:23:46Z" name="beforeClass" finished-at="2021-06-27T12:23:46Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:qa.testscripts.AUT1@63f259c3]" started-at="2021-06-27T12:23:46Z" name="beforeMethod" finished-at="2021-06-27T12:23:56Z" duration-ms="10194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="VerifySorting()[pri:0, instance:qa.testscripts.AUT1@63f259c3]" started-at="2021-06-27T12:23:56Z" name="VerifySorting" finished-at="2021-06-27T12:23:56Z" duration-ms="18" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in] but found [Home page]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in] but found [Home page]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at qa.pages.MagentoPage.TitleVerification(MagentoPage.java:29)
at qa.testscripts.AUT1.VerifySorting(AUT1.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifySorting -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:qa.testscripts.AUT1@63f259c3]" started-at="2021-06-27T12:23:56Z" name="afterMethod" finished-at="2021-06-27T12:24:00Z" duration-ms="4089" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:qa.testscripts.AUT1@63f259c3]" started-at="2021-06-27T12:24:00Z" name="afterSuite" finished-at="2021-06-27T12:24:01Z" duration-ms="687" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- qa.testscripts.AUT1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
